# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e0fc18ec6f715444e2ebf252b0f1982f"
name = "InvoiceGen â€‘ B2B PDF Invoice"
application_url = "https://invoice-generator-r60s.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[webhooks.privacy_compliance]
customer_data_request_url = "https://invoice-generator-r60s.onrender.com/webhooks/customers/data_request"
customer_deletion_url = "https://invoice-generator-r60s.onrender.com/webhooks/customers/redact"
shop_deletion_url = "https://invoice-generator-r60s.onrender.com/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_customers"

[auth]
redirect_urls = [ 
  "https://invoice-generator-r60s.onrender.com/auth/callback",
  "https://invoice-generator-r60s.onrender.com/auth/shopify/callback",
  "https://invoice-generator-r60s.onrender.com/api/auth/callback"
]
